# Flask Application Configuration

hosts:
  - "127.0.0.1"

port: 5000
debug: true

logging:
  level: "INFO"
  file: "/var/log/vezor.log"

security:
  csrf_enabled: false
  secret_key: "super_secret_key"

cors:
  allowed_origins:
    - "*"
# Additional configuration sections can be added as needed.
# Example of email configuration:
# email:
#   smtp_server: "smtp.mailtrap.io"
#   smtp_port: 587
#   username: "email_user"
#   password: "email_password"
#   from_address: "noreply@yourdomain.com"
